apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
spec:
    replicas: 3
    selector:
       matchLabels:
          app: nginx
    template:
       metadata:
          labels:
             app: nginx
       spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service 
metadata:
   name: nginx
spec:
   type: NodePort
   selector:
         app: nginx
   ports:
   - port: 8080
     targetPort: 3000
     nodePort: 31000
     protocol: TCP
